name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Installing Poetry
        run: snok/install-poetry@v1
        with:
          virtualenvs-in-path: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}
        
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
      
      - name: Running Lint
        run: poetry run make lint
        
      - name: Running Sec Test
        run: poetry run make test
