name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: poetry
      run: poetry install
      
    - name: Install dependencies
      run: make
    
    - name: Run test
      run: make test
      
    - name: Run sec
      run: make sec
